## The example of _config.yml can be found here: https://github.com/academicpages/academicpages.github.io/blob/master/_config.yml

title                    : "Zheng Zhang / Astrophysicist and cosmologist"
title_separator          : "-"
name                     : &name "Zheng Zhang"
description              : &description "I am a physicist who thrives on the beauty of mathematics and a keen observer drawn to the power of theory."
show_downloads           : true

baseurl                  : "" # Base URL for the site
url                      : "https://zh-zhang.com/"

date_format              : "%b %-d, %Y"

author:
  # Biographic information
  avatar                 : "profile.png"
  pronouns               : "he/him"
  bio                    : "Physicist. Lover of math, observer of theory."
  
  arxiv                  :
  googlescholar          :
  orcid                  :

  github                 :
  
plugins:
  - jekyll-target-blank

# target-blank:
#     rel: nofollow

header_page_refs: ['now', 'about', 'contact']
